name: Release notification
on:
  pull_request:
    branches:
      - DO_NOT_EXECUTE_THIS_WORKFLOW

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/release-notifier-action@v1
        with:
          app_id: ${{ secrets.RELEASE_NOTIFIER_APP_ID }}
          private_key: ${{ secrets.RELEASE_NOTIFIER_APP_PRIVATE_KEY }}
          dispatch_event_type: 'release:primer/view_components'
